/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef PKTFWDNORMDISTHLISTRMITMQUERY_H
#define PKTFWDNORMDISTHLISTRMITMQUERY_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace pktfwdnormdisthlistrmitmquery {

class PktfwdNormDistHlistRmitmQuery : public RapidNetApplicationBase
{
public:
  static const string BASEQUERY;
  static const string BASERETURN;
  static const string CHILDWAIT;
  static const string EPRETURN;
  static const string ERRETURN;
  static const string ERULEQUERY;
  static const string EPACKETTEMP;
  static const string ERECVPACKETTEMP;
  static const string FLOWENTRY;
  static const string INITPACKET;
  static const string INITPROVQUERY;
  static const string LINK;
  static const string PITERATE;
  static const string PQLIST;
  static const string PRESULTTMP;
  static const string PRETURN;
  static const string PACKET;
  static const string PROV;
  static const string PROVQUERY;
  static const string PROVROOT;
  static const string RITERATE;
  static const string RQLIST;
  static const string RRESULTTMP;
  static const string RRETURN;
  static const string RECORDPROV;
  static const string RECORDSD;
  static const string RECVCOUNT;
  static const string RECVPACKET;
  static const string RULEEXEC;
  static const string RULEQUERY;

  static TypeId GetTypeId (void);

  PktfwdNormDistHlistRmitmQuery ();

  virtual ~PktfwdNormDistHlistRmitmQuery ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R00Eca1Ins (Ptr<Tuple> initPacket);

  virtual void R00Eca1Del (Ptr<Tuple> initPacket);

  virtual void R01Eca1Ins (Ptr<Tuple> link);

  virtual void R01Eca1Del (Ptr<Tuple> link);

  virtual void R03Eca1Ins (Ptr<Tuple> flowEntry);

  virtual void R03Eca1Del (Ptr<Tuple> flowEntry);

  virtual void Prov_rs1_1_eca (Ptr<Tuple> packet);

  virtual void Prov_rs1_2_eca (Ptr<Tuple> epacketTemp);

  virtual void Prov_rs1_3_eca (Ptr<Tuple> epacketTemp);

  virtual void Prov_rh1_1Eca0Ins (Ptr<Tuple> initPacket);

  virtual void Prov_rh1_1Eca1Ins (Ptr<Tuple> flowEntry);

  virtual void Prov_rh1_1Eca2Ins (Ptr<Tuple> link);

  virtual void Prov_rh2_1_eca (Ptr<Tuple> packet);

  virtual void Prov_rh2_2_eca (Ptr<Tuple> erecvPacketTemp);

  virtual void Prov_rh2_3_eca (Ptr<Tuple> erecvPacketTemp);

  virtual void Prov_rh2_5_eca (Ptr<Tuple> recvPacket);

  virtual void Edb1_eca (Ptr<Tuple> baseQuery);

  virtual void Idb1_eca (Ptr<Tuple> provQuery);

  virtual void Idb2_eca (Ptr<Tuple> provQuery);

  virtual void Idb3_eca (Ptr<Tuple> provQuery);

  virtual void Idb4_eca (Ptr<Tuple> pIterate);

  virtual void Idb5_eca (Ptr<Tuple> pIterate);

  virtual void Idb6_eca (Ptr<Tuple> eRuleQuery);

  virtual void Idb7_eca (Ptr<Tuple> rReturn);

  virtual void Idb8Eca0Ins (Ptr<Tuple> pResultTmp);

  virtual void Idb8Eca1Ins (Ptr<Tuple> pQList);

  virtual void Idb9_eca (Ptr<Tuple> ePReturn);

  virtual void Rv1_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv2_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv3_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv4_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv5_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv6_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv7_eca (Ptr<Tuple> rIterate);

  virtual void Rv8_eca (Ptr<Tuple> rIterate);

  virtual void Rv9_eca (Ptr<Tuple> baseReturn);

  virtual void Rv10_eca (Ptr<Tuple> rReturn);

  virtual void Rv11Eca0Ins (Ptr<Tuple> rResultTmp);

  virtual void Rv11Eca1Ins (Ptr<Tuple> childWait);

  virtual void Rv11Eca3Ins (Ptr<Tuple> rQList);

  virtual void Rv12Eca0Ins (Ptr<Tuple> rResultTmp);

  virtual void Rv12Eca1Ins (Ptr<Tuple> childWait);

  virtual void Rv12Eca3Ins (Ptr<Tuple> rQList);

  virtual void Rv13_eca (Ptr<Tuple> eRReturn);

  virtual void Q1_eca (Ptr<Tuple> recvPacket);

  virtual void Q2_eca (Ptr<Tuple> recvCount);

  virtual void Q3_eca (Ptr<Tuple> recvCount);

  virtual void Q4Eca0Ins (Ptr<Tuple> initProvQuery);

  virtual void Q5_eca (Ptr<Tuple> pReturn);

};

} // namespace pktfwdnormdisthlistrmitmquery
} // namespace rapidnet
} // namespace ns3

#endif // PKTFWDNORMDISTHLISTRMITMQUERY_H
