## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-norm-prov-enabled', ['internet-stack'])
    module.source = [
        'pktfwd-norm-prov-enabled.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-norm-prov-enabled'
    headers.source = [
        'pktfwd-norm-prov-enabled.h',
        'pktfwd-norm-prov-enabled-helper.h',
        ]
